export const SET_IS_LOGIN = 'SET_IS_LOGIN'
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE'

// Forget password 
export const SET_IS_OPEN_FORGET_PASSWORD_MODAL = 'SET_IS_OPEN_FORGET_PASSWORD_MODAL'
export const SET_FORGET_PASSWORD_USERNAME = 'SET_FORGET_PASSWORD_USERNAME'
export const SET_NEW_PASSWORD = 'SET_NEW_PASSWORD'
export const SET_MODAL_TITLE = 'SET_MODAL_TITLE'
export const SET_CURRENT_STEP_FORGET_PASSWORD_MODAL = 'SET_CURRENT_STEP_FORGET_PASSWORD_MODAL'
export const SET_NUM_CODE_1 = 'SET_NUM_CODE_1'
export const SET_NUM_CODE_2 = 'SET_NUM_CODE_2'
export const SET_NUM_CODE_3 = 'SET_NUM_CODE_3'
export const SET_NUM_CODE_4 = 'SET_NUM_CODE_4'
export const SET_NUM_CODE_5 = 'SET_NUM_CODE_5'
export const SET_NUM_CODE_6 = 'SET_NUM_CODE_6'
export const SET_IS_CORRECT_CODE = 'SET_IS_CORRECT_CODE'
export const SET_CORRECT_CODE = 'SET_CORRECT_CODE'
export const SET_CLOSE_FORGET_PASSWORD_MODAL_TIME = 'SET_CLOSE_FORGET_PASSWORD_MODAL_TIME'
export const COUNTDOWN_CLOSE_FORGET_PASSWORD_MODAL_TIME = 'COUNTDOWN_CLOSE_FORGET_PASSWORD_MODAL_TIME'
export const SET_CODE_TIMEOUT = 'SET_CODE_TIMEOUT'
export const COUNTDOWN_CODE_TIMEOUT = 'COUNTDOWN_CODE_TIMEOUT'

// Register
export const SET_IS_OPEN_REGISTER_MODAL = 'SET_IS_OPEN_REGISTER_MODAL'
export const SET_REGISTER_STATUS = 'SET_REGISTER_STATUS'
export const SET_CITIES = 'SET_CITIES'
export const SET_DISTRICTS = 'SET_DISTRICTS'
export const SET_WARDS = 'SET_WARDS'
export const SET_CITY_CODE = 'SET_CITY_CODE'
export const SET_DISTRICT_CODE = 'SET_DISTRICT_CODE'
export const SET_WARD_CODE = 'SET_WARD_CODE'


